---
- name: Install Package
  hosts: all
  vars:
  - package_name: httpd

  tasks:
  
    - name: Ansible remove file
      file:
        path: "/etc/yum.repos.d/cd.repo"
        state: absent

    - name: Enregistrement a access red hat avec la cle d'activation
      redhat_subscription:
        state: present
        activationkey: "infra-tour-france"
        org_id: "5318211"
      ignore_errors: True
      
    - name: install package {{ package_name }}
      yum: name={{ package_name }} state=present
